name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Package app for Windows
        if: runner.os == 'Windows'
        run: npx electron-builder --win --x64 --publish never

      - name: Package app for macOS
        if: runner.os == 'macOS'
        run: npx electron-builder --mac --x64 --publish never

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/MediaSorter-*.dmg
            dist/MediaSorter Setup.*.exe
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}